
sudo: false

language: java
matrix:
  include:
  - jdk: oraclejdk8
    dist: trusty
  - jdk: openjdk8
  - jdk: openjdk9
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk12
  - jdk: openjdk13
  
before_install:
 - "export JAVA_OPTS=-Xmx1500m"
 - "echo JAVA_OPTS=$JAVA_OPTS"
 - "export MAVEN_OPTS=-Xmx1500m"
 - "echo MAVEN_OPTS=$MAVEN_OPTS"
 - "export _JAVA_OPTIONS=-Xmx1500m"
 - "echo _JAVA_OPTIONS=$_JAVA_OPTIONS"
 
install: mvn dependency:resolve -B -V

cache:
  directories:
  - $HOME/.m2

script:
 - travis_wait 30 mvn install

after_failure:
  - cat */target/surefire-reports/*.txt
